version: '3'

services:
    app:
        image: zephinzer/golang-dev:latest
        env_file: 
            - db.env
        ports: 
            - 80:80
            - 443:443
        entrypoint: ["start"]
        volumes:
            - ./:/go/src/app # for mapping source files
    db:
        image: postgres:10.1
        env_file: 
            - db.env
        volumes: 
            - ./db-init:/docker-entrypoint-initdb.d/